[0m08:06:18.164791 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fbb6dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112b93490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112bafd90>]}


============================== 08:06:18.169715 | 313125e6-7ec5-425c-bc22-e47fdc9c6d84 ==============================
[0m08:06:18.169715 [info ] [MainThread]: Running with dbt=1.8.1
[0m08:06:18.170171 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'False', 'cache_selected_only': 'False', 'profiles_dir': '/Users/benw/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt parse --no-partial-parse', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:06:18.170605 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/benw/GitHub/mf-translate/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:06:18.172683 [debug] [MainThread]: Resource report: {"command_name": "parse", "command_wall_clock_time": 0.113343, "process_user_time": 0.796335, "process_kernel_time": 0.13813, "process_mem_max_rss": "102756352", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m08:06:18.173203 [debug] [MainThread]: Command `dbt parse` failed at 08:06:18.173117 after 0.11 seconds
[0m08:06:18.173534 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112b537d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112b93490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112b92110>]}
[0m08:06:18.173800 [debug] [MainThread]: Flushing usage events
[0m08:18:15.145940 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111504e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111506490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11153d350>]}


============================== 08:18:15.150853 | e99dcb49-f33f-469e-abbe-db666833046b ==============================
[0m08:18:15.150853 [info ] [MainThread]: Running with dbt=1.8.1
[0m08:18:15.151312 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'False', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/benw/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt parse --no-partial-parse', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m08:18:15.151733 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/benw/GitHub/mf-translate/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:18:15.153752 [debug] [MainThread]: Resource report: {"command_name": "parse", "command_wall_clock_time": 0.09143, "process_user_time": 0.782165, "process_kernel_time": 0.133556, "process_mem_max_rss": "101380096", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m08:18:15.154238 [debug] [MainThread]: Command `dbt parse` failed at 08:18:15.154161 after 0.09 seconds
[0m08:18:15.154555 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1115066d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1113c7fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b5bdb10>]}
[0m08:18:15.154815 [debug] [MainThread]: Flushing usage events
